### ISSUE TITLE
[Feature] Custom positioning

### ISSUE THREAD

**Issue by NickLarsenNZ** [RaoulMeyer/diagram-as-code#1]
I really like this idea. I wondered what happens as the diagram gets more complex and whether objects can have their layout customised.

Maybe taking a lambda, with the default being: `(x, y) => {x, y}` (if that works with the underlying rendering library).

**Comment by RaoulMeyer** [comment]
Hi, thanks for your suggestion! I've looked into it, and decided to add a way to specify a layer for each node. This way, you have some control over the layout but don't have to worry about actual pixels.

See https://github.com/RaoulMeyer/diagram-as-code/commit/8731585a18f5ee5774aa26b140f7915e417e497c for the change.

I think this will be sufficient for most cases, if you have a case where it's not then please let me know!
