### ISSUE TITLE
[Feature] Network state of mind :) 

### ISSUE THREAD

**Issue by tpoindessous** [RaoulMeyer/diagram-as-code#2]
Hi

I like very much your project and I think I will try it for several diagrams.

But I'm an Ops guy and I can't cope with data flow (getDataFrom and sendDataTo) :) I'm more used to network flux ( OpenConnectionTo and maybe GetConnectionFrom).

I know the diagram will be the same but the logic is quite different :
```
client.getsDataFrom(loadbalancer);
loadbalancer.getsDataFrom(webserver);
webserver.getsDataFrom(databases);
```
VS
```
client.openConnectionTo(loadbalancer);
loadbalancer.openConnectionTo(webserver);
webserver.openConnectionTo(databases);
```

Do you think you could add these methods (with your own choice of wording) in your project ?

Thanks !

**Comment by RaoulMeyer** [comment]
Hi @tpoindessous, glad you like it! I can imagine that the methods I've provided aren't enough in every situation.

I've now added a more generic solution to this issue. You can use any method that ends with `to`, `from` or `with` and they will behave how you'd expect them to (So arrow `to` the argument, arrow `from` the argument, arrow both ways).

Thanks for your suggestion. If you have any other ideas, let me know!
